// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news/news.proto

package pers.lbf.news.proto;

public final class NewsProto {
  private NewsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017news/news.proto\022\004news\032\026news/newsMessag" +
      "e.proto2,\n\013NewsService\022\035\n\004List\022\010.NewsReq" +
      "\032\t.NewsResp\"\000B\"\n\023pers.lbf.news.protoB\tNe" +
      "wsProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pers.lbf.news.proto.NewsProtoMessage.getDescriptor(),
        });
    pers.lbf.news.proto.NewsProtoMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
