// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sms/smsService.proto

package pers.lbf.news.proto;

public final class SmsProto {
  private SmsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024sms/smsService.proto\022\003sms\032\024sms/smsMess" +
      "age.proto23\n\nSmsService\022%\n\004Send\022\013.SmsSen" +
      "dReq\032\014.SmsSendResp\"\0000\001B!\n\023pers.lbf.news." +
      "protoB\010SmsProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pers.lbf.news.proto.SmsProtoMessage.getDescriptor(),
        });
    pers.lbf.news.proto.SmsProtoMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
