// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sms/smsService.proto

package pers.lbf.news.proto;

public final class SmsProto {
  private SmsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024sms/smsService.proto\022\003sms\032\024sms/smsMess" +
      "age.proto2\237\001\n\nSmsService\022%\n\004Send\022\013.SmsSe" +
      "ndReq\032\014.SmsSendResp\"\0000\001\0224\n\013CreatePhone\022\017" +
      ".CreatePhoneReq\032\020.CreatePhoneResp\"\000(\001\0224\n" +
      "\rCreateAndSend\022\t.PhoneReq\032\022.CreateAndSen" +
      "dResp\"\000(\0010\001B!\n\023pers.lbf.news.protoB\010SmsP" +
      "rotoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pers.lbf.news.proto.SmsProtoMessage.getDescriptor(),
        });
    pers.lbf.news.proto.SmsProtoMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
